services:
  db:
    image: postgres:16-alpine
    container_name: f1_db
    environment:
      POSTGRES_USER: f1_user
      POSTGRES_PASSWORD: f1_password
      POSTGRES_DB: f1_database
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  
  redis:
    image: redis:7-alpine
    container_name: f1_redis
    ports:
      - "6379:6379"

  app:
    depends_on:
      - db
      - redis
    build: .
    container_name: f1_app
    ports:
      - "8000:8000"
    environment:
      DB_URL: ${DB_URL}
      REDIS_URL: ${REDIS_URL}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ALGORITHM: ${JWT_ALGORITHM}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
      REFRESH_TOKEN_EXPIRE_DAYS: ${REFRESH_TOKEN_EXPIRE_DAYS}
      ENVIRONMENT: ${ENVIRONMENT}


volumes:
  db_data:
