"""created user model

Revision ID: a6c1eb602edc
Revises: 
Create Date: 2026-08-13 20:52:15.163755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6c1eb602edc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('f1_team', sa.Enum('MERCEDES', 'FERRARI', 'RED_BULL', 'MCLAREN', 'ALPINE', 'ASTON_MARTIN', 'RACING_BULLS', 'HAAS', 'WILLIAMS', 'AUDI', 'CADILLAC', name='f1teams'), nullable=False),
    sa.Column('rank', sa.Enum('ROOKIE', 'AMATEUR', 'PRO', 'WORLD_CLASS', 'CHAMPION', name='userrank'), nullable=True),
    sa.Column('rank_elo', sa.Integer(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
